BoxLayout:
    orientation: 'vertical'
    TextInput:
        id: input_number
        text: ''
        font_size: 20
        multiline: False
    Button:
        text: 'Square'
        # the following line specifies the function in the app class to call when the button is pressed
        on_press: app.handle_calculate(int(input_number.text))
    Label:
        id: output_label
        font_size:20
        color: (0, 1, 1, 1)